---
resources:
- name: resource-vm
  type: git
  source:
    uri: https://github.com/AlLau/concourse-tutorial.git
    
jobs:
- name: job-vm
  public: true
  plan:
  - get: resource-vm
    trigger: true
  - task: spinup-vm
    file: resource-vm/pipelines/tasks/spinupvms.yml
