---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "16.04"

inputs:
  - name: concourse-tutorial
    path: .

outputs:
  - name: list_of_vms
    path: .

run:
  path: concourse-tutorial/pipelines/bin/spinupvms
