---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu, tag: "16.04"}

inputs:
  - name: resource-vm
    path: .

outputs:
  - name: list-vm

run:
  path: pipelines/bin/spinupvms
