---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "16.04"

inputs:
  - name: pipelines
    path: vminput

outputs:
  - name: list_of_vms
    path: vmoutput

run:
  path: pipelines/bin/spinupvms
